/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace customer {
    export interface HandleCustomerService {
        createReportIdWall(
            data: CrateReportIdWallRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<EmptyMessage>;
        validateReportIdWall(
            data: ValidateReportIdWallRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<EmptyMessage>;
    }
    export interface ValidateReportIdWallRequest {
        numReport?: string;
    }
    export interface CrateReportIdWallRequest {
        cpf?: string;
        sdkToken?: string;
        imageUrl?: string;
        type?: string;
        privateUrl?: string;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface EmptyMessage {
    }
}

