/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace user {
    export interface HandleUserService {
        createUser(
            data: CreateUserRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<EmptyMessage>;
    }
    export interface CreateUserRequest {
        cpf?: string;
        name?: string;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface EmptyMessage {
    }
}

